default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: cfb_line_generator_development

test: &TEST
  <<: *default
  database: cfb_line_generator_test

production:
  adapter: postgresql
  encoding: utf8
  database: cfb_line_generator_production
