development:
  adapter: postgresql
  encoding: utf8
  database: cfb_line_generator_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: cfb_line_generator_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: cfb_line_generator_production
  pool: 5
  username:
  password:
